# Gabut Package Info
name: brainly-api
packageManager: npm # package.json
logo: null
urls: 
  - https://npmjs.com/package/brainly-api
  - https://github.com/dhanuprys/brainly-api
isVisible: true
languanges:
  - javascript
  - typescript
